apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:1
          ports:
            - containerPort: 8080